/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultIdRouteImport } from './routes/vault.$id'
import { Route as ProfileWalletRouteImport } from './routes/profile.$wallet'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIdRoute = VaultIdRouteImport.update({
  id: '/vault/$id',
  path: '/vault/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileWalletRoute = ProfileWalletRouteImport.update({
  id: '/profile/$wallet',
  path: '/profile/$wallet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/profile/$wallet': typeof ProfileWalletRoute
  '/vault/$id': typeof VaultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/profile/$wallet': typeof ProfileWalletRoute
  '/vault/$id': typeof VaultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/profile/$wallet': typeof ProfileWalletRoute
  '/vault/$id': typeof VaultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/dashboard'
    | '/docs'
    | '/profile/$wallet'
    | '/vault/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/dashboard'
    | '/docs'
    | '/profile/$wallet'
    | '/vault/$id'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/dashboard'
    | '/docs'
    | '/profile/$wallet'
    | '/vault/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  ProfileWalletRoute: typeof ProfileWalletRoute
  VaultIdRoute: typeof VaultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$id': {
      id: '/vault/$id'
      path: '/vault/$id'
      fullPath: '/vault/$id'
      preLoaderRoute: typeof VaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$wallet': {
      id: '/profile/$wallet'
      path: '/profile/$wallet'
      fullPath: '/profile/$wallet'
      preLoaderRoute: typeof ProfileWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  ProfileWalletRoute: ProfileWalletRoute,
  VaultIdRoute: VaultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
